AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  firstLambda

  Sample SAM Template for firstLambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 128

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HelloWorldFunction
     # Handler: helloworld.App::hello
      Handler: com.eapen.aws.lambda.DataTypes::coldStartBasics
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 6
      Environment:
        Variables:
          restapiurl: testurl
     