version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "studentgrading"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mdtw3dsxf0ru"
s3_prefix = "studentgrading"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
