AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  customerapi

  Sample SAM Template for customerapi

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: java11
    Architectures:
      - x86_64
    MemorySize: 512
    Timeout: 60
    Environment:
      Variables:
        CUSTOMER_TABLE: !Ref CustomerTable

Resources:
  CustomerTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: firstName
        Type: String
  CreateCustomerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: customerapi
      Handler: com.aws.lambda.api.CreateCustomerLambda::createCustomer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CustomerTable
      Events: 
        CustomerEvents:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /customer
            Method: post
  ReadCustomerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: customerapi
      Handler: com.aws.lambda.api.ReadCustomerLambda::getCustomer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CustomerTable  
      Events: 
        CustomerEvents:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /customer
            Method: get
